name: Fetch Daily Tweets

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6AM UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run tweet fetcher
        run: python scripts/fetch_tweets.py
        env:
          TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}

      - name: Commit and push tweets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "bot@users.noreply.github.com"
          git add public/community_feed/
          git commit -m "Update daily tweet snapshot"
          git push
        continue-on-error: true
